version: "3.9"

services:
  api:
    build:
      context: ./backend-research-app      # uses backend-research-app/Dockerfile
    image: backend-research:latest
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - ./backend-research-app/.env        # has OPENAI_BASE=http://host.docker.internal:1234/v1
    restart: unless-stopped

  web:
    build:
      context: ./frontend                  # uses frontend/Dockerfile
      args:
        # Use ONE of these depending on your tooling:
        # For CRA:
        REACT_APP_API_URL: "http://localhost:8000"
        # For Vite (remove the CRA arg and keep this one):
        # VITE_API_URL: "http://localhost:8000"
    image: frontend-app:latest
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
