version: "3.9"

services:
  # =========================
  # Backend API (FastAPI)
  # =========================
  api:
    build:
      context: ./backend-research-app      # Backend Dockerfile location
    image: backend-research:latest
    container_name: ai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend-research-app/.env        # Contains PINECONE_API_KEY, OPENAI_BASE, model names
    restart: unless-stopped

  # =========================
  # Frontend (React)
  # =========================
  web:
    build:
      context: ./frontend                  # Frontend Dockerfile location
      args:
        REACT_APP_API_URL: "http://localhost:8000"   # API endpoint for React
    image: frontend-app:latest
    container_name: ai-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
